### ISSUE TITLE
TypeError: descriptor 'get_info' requires a 'cec2013lsgo.cec2013.Benchmark' object but received a 'int'

### ISSUE THREAD

**Issue by Leo-Q-316** [dmolina/cec2013lsgo#1]
`>>> from cec2013lsgo.cec2013 import Benchmark
>>> bench = Benchmark
>>> bench.get_info(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor 'get_info' requires a 'cec2013lsgo.cec2013.Benchmark' obje                                     ct but received a 'int'
`

**Comment by dmolina** [comment]
The problems is the lack of parenthesis.  This should work:

```python
from cec2013lsgo.cec2013 import Benchmark
bench = Benchmark()
bench.get_info(2)
```
